export enum ErrorCode {
	URL_NOT_FOUND = "URL_NOT_FOUND",
	URL_EXPIRED = "URL_EXPIRED",
	URL_DISABLED = "URL_DISABLED",
	SHORT_CODE_CONFLICT = "SHORT_CODE_CONFLICT",
	PASSWORD_PROTECTED = "PASSWORD_PROTECTED",
	INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
}
