packages:
  - apps/*
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lefthook: true
  sharp: true
  vue-demi: true
  workerd: true

catalogs:
  build:
    turbo: ^2.8.14
    "@nuxt/kit": ^4.3.1
  lint:
    oxlint: ^1.51.0
    oxlint-tsgolint: ^0.16.0
    oxfmt: ^0.36.0
  script:
    lefthook: ^2.1.2
  frontend:
    vue: ^3.5.29
    unocss: ^66.6.6
    sb-addon-vue-csf: ^0.0.2
