packages:
  - apps/*
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lefthook: true
  sharp: true
  vue-demi: true
  workerd: true

catalogs:
  build:
    turbo: ^2.8.10
  lint:
    oxlint: ^1.51.0
    oxlint-tsgolint: ^0.16.0
    oxfmt: ^0.36.0
  script:
    lefthook: ^2.1.2
  frontend:
    unocss: ^66.6.6
